"""empty message

Revision ID: 8678136e6612
Revises: 2556d941f07e
Create Date: 2020-06-06 22:02:11.407008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8678136e6612'
down_revision = '2556d941f07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'timestamp')
    # ### end Alembic commands ###
